from __future__ import annotations

import os
import sys


def configure_utf8_stdio() -> None:
    """Force UTF-8 for console output when possible.

    Windows terminals, Anaconda shells, and pytest subprocess pipes can default to
    legacy encodings such as cp1252. The reports generated by this project are
    Chinese markdown, so direct print() calls may otherwise raise
    UnicodeEncodeError. This helper is intentionally safe: if reconfigure is not
    available, it falls back to setting environment hints for child processes.
    """
    os.environ.setdefault("PYTHONIOENCODING", "utf-8")
    os.environ.setdefault("PYTHONUTF8", "1")

    for stream_name in ("stdout", "stderr"):
        stream = getattr(sys, stream_name, None)
        if stream is None:
            continue
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except Exception:
                # Some wrapped streams do not allow reconfiguration. In that case
                # the environment variables above still help child processes.
                pass
